# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Scientific Machine Learning for Engineers
author: N. Adams, L. Paehler, A. Toshev
copyright: "2022,2023,2024"
logo: logo.png
exclude_patterns: [_build, venv, data, README.md]

launch_buttons:
  colab_url: https://colab.research.google.com
  binderhub_url: "" # without this line the default is not empty

# Do not force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off # force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tumaer/SciML  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)
  # path_to_book: docs  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false # restart chapter numbering between parts

# all extensions: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-extensions
parse:
  myst_enable_extensions:
    - amsmath # enable direct parsing of amsmath LaTeX equations
    - dollarmath # enable dollar delimited math
    - linkify # automatically identify “bare” web URLs and add hyperlinks
#     - html_image # convert any isolated img tags to the representation used in sphinx
#     - colon_fence # enable using ::: delimiters to denote directives, instead of ```

# to expand embedded files, i.e. sections. Reference:
# https://github.com/executablebooks/jupyter-book/issues/1134
sphinx:
  recursive_update: true
  config:
    html_theme_options:
      show_navbar_depth: 2
    bibtex_reference_style: author_year
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js